#include <GlassHelix/artifacts/nf1_replay.hh>
#include <Cellerator/compute/operation/differential/local_arithmetic.hh>
#include <charconv>
#include <array>
#include <cctype>
#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>
namespace glasshelix::artifacts { namespace { namespace df=cellerator::compute::differential; namespace nn=cellerator::compute::native_numeric;
bool fail(std::string*e,const char*m){if(e)*e=m;return false;} bool atom(const std::string&s){return !s.empty()&&s.find_first_of("\n\r|,") == std::string::npos;}
bool sha(const std::string&s){if(s.size()!=40)return false;for(char c:s)if(!std::isxdigit(static_cast<unsigned char>(c)))return false;return true;}
bool blocks(const std::vector<std::string>&v){for(const auto&s:v){auto h=s.find('#'),a=s.find('@');if(!atom(s)||h==0||a==std::string::npos||a<h+2)return false;}return !v.empty();}
bool split(const std::string&s,char c,std::vector<std::string>*o){std::size_t p=0;for(;;){auto q=s.find(c,p);o->push_back(s.substr(p,q-p));if(q==std::string::npos)return true;p=q+1;}}
bool status(const std::string&s,nf1_run_status*o){if(s=="pending")*o=nf1_run_status::pending;else if(s=="failed")*o=nf1_run_status::failed;else if(s=="succeeded_empty")*o=nf1_run_status::succeeded_empty;else if(s=="succeeded_output")*o=nf1_run_status::succeeded_output;else return false;return true;}
bool floats(const std::string&s,std::vector<float>*o){if(s.empty())return true;std::vector<std::string>v;split(s,',',&v);for(const auto&t:v){float x{};auto [p,e]=std::from_chars(t.data(),t.data()+t.size(),x);if(e!=std::errc{}||p!=t.data()+t.size()||!std::isfinite(x))return false;o->push_back(x);}return true;}
}
const char* status_name(nf1_run_status s) noexcept {switch(s){case nf1_run_status::pending:return"pending";case nf1_run_status::failed:return"failed";case nf1_run_status::succeeded_empty:return"succeeded_empty";case nf1_run_status::succeeded_output:return"succeeded_output";}return"invalid";}
bool validate(const nf1_replay_record&r,std::string*e) noexcept {if(r.schema!=1)return fail(e,"incompatible schema");if(!atom(r.numerical_policy)||r.numerical_policy!="f32-rne-propagate"||!sha(r.glasshelix_source)||!sha(r.cellerator_source)||!blocks(r.registered_blocks))return fail(e,"invalid NF1 definition metadata");for(float x:r.logical_inputs)if(!std::isfinite(x))return fail(e,"nonfinite input");if(r.status==nf1_run_status::failed)return atom(r.failure)?true:fail(e,"failed record needs failure");if(!r.failure.empty())return fail(e,"unexpected failure");if(r.status==nf1_run_status::succeeded_output&&r.logical_output.empty())return fail(e,"output status needs output");if(r.status!=nf1_run_status::succeeded_output&&!r.logical_output.empty())return fail(e,"unexpected output");return true;}
bool write_nf1_replay(const std::string&p,const nf1_replay_record&r,std::string*e) noexcept {if(!validate(r,e))return false;std::ofstream o(p);if(!o)return fail(e,"cannot open artifact");o<<"GH_NF1_REPLAY|1|"<<status_name(r.status)<<'|'<<r.numerical_policy<<'|'<<r.glasshelix_source<<'|'<<r.cellerator_source<<'|'<<r.failure<<'|';for(auto&i:r.registered_blocks)o<<i<<',';o<<'|';for(float x:r.logical_inputs)o<<std::to_string(x)<<',';o<<'|';for(float x:r.logical_output)o<<std::to_string(x)<<',';return bool(o)?true:fail(e,"write failed");}
bool read_nf1_replay(const std::string&p,nf1_replay_record*r,std::string*e) noexcept {std::ifstream in(p);std::string line,extra;if(!r||!in||!std::getline(in,line)||std::getline(in,extra))return fail(e,"missing/corrupt artifact");std::vector<std::string>f;split(line,'|',&f);if(f.size()!=10||f[0]!="GH_NF1_REPLAY"||f[1]!="1")return fail(e,"incompatible artifact");nf1_replay_record x{};if(!status(f[2],&x.status))return fail(e,"invalid status");x.numerical_policy=f[3];x.glasshelix_source=f[4];x.cellerator_source=f[5];x.failure=f[6];if(!f[7].empty()){split(f[7].substr(0,f[7].size()-1),',',&x.registered_blocks);}if(!floats(f[8].empty()?"":f[8].substr(0,f[8].size()-1),&x.logical_inputs)||!floats(f[9].empty()?"":f[9].substr(0,f[9].size()-1),&x.logical_output)||!validate(x,e))return false;*r=std::move(x);return true;}
bool replay_defined_operation(const nf1_replay_record&r,std::vector<float>*out,std::string*e) noexcept {if(!out||!validate(r,e)||r.status!=nf1_run_status::succeeded_output)return fail(e,"record is not replayable output");if(r.registered_blocks[0]!="local-add#10@1"||r.logical_inputs.size()!=4)return fail(e,"unsupported registered definition");std::array<float,1>a{r.logical_inputs[0]},b{r.logical_inputs[1]},da{r.logical_inputs[2]},db{r.logical_inputs[3]},y{};df::local_binding<float>x{{a},{b},{da},{db},{},{y},{},{}};if(df::local_jvp(nn::local_operation::add,x)!=nn::local_status::success)return fail(e,"native CE operation refused");out->assign(y.begin(),y.end());return true;}
}
