#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <Cellerator/compute/operation/differential/local_arithmetic.hh>
#include <span>
#include <string_view>
#include <vector>
namespace df=cellerator::compute::differential; namespace nn=cellerator::compute::native_numeric;
namespace {
struct view { Py_buffer buffer{}; ~view(){if(buffer.obj)PyBuffer_Release(&buffer);} };
bool f32_1d(PyObject* object,view* out,const char* name){if(PyObject_GetBuffer(object,&out->buffer,PyBUF_FORMAT|PyBUF_STRIDES)<0)return false;const auto&b=out->buffer;if(b.ndim!=1||b.itemsize!=sizeof(float)||!b.format||std::string_view(b.format)!="f"||b.strides[0]!=sizeof(float)){PyErr_Format(PyExc_TypeError,"%s must be a contiguous one-dimensional float32 buffer",name);return false;}return true;}
bool same(Py_ssize_t n,const view&v,const char*name){if(v.buffer.len!=n*Py_ssize_t(sizeof(float))){PyErr_Format(PyExc_ValueError,"%s length mismatch",name);return false;}return true;}
bool op(PyObject*name,nn::local_operation*out){const char*s=PyUnicode_AsUTF8(name);if(!s)return false;if(std::string_view(s)=="add")*out=nn::local_operation::add;else if(std::string_view(s)=="multiply")*out=nn::local_operation::multiply;else if(std::string_view(s)=="tanh")*out=nn::local_operation::tanh;else {PyErr_SetString(PyExc_ValueError,"operation must be add, multiply, or tanh");return false;}return true;}
PyObject* jvp(PyObject*,PyObject*args){PyObject *name,*left,*right,*dl,*dr;if(!PyArg_ParseTuple(args,"OOOOO",&name,&left,&right,&dl,&dr))return nullptr;nn::local_operation operation{};if(!op(name,&operation))return nullptr;view a,b,da,db;if(!f32_1d(left,&a,"left")||!f32_1d(right,&b,"right")||!f32_1d(dl,&da,"left_direction")||!f32_1d(dr,&db,"right_direction"))return nullptr;const auto n=a.buffer.len/sizeof(float);if(!same(n,b,"right")||!same(n,da,"left_direction")||!same(n,db,"right_direction"))return nullptr;std::vector<float> output(n);const bool unary=operation==nn::local_operation::tanh;df::local_binding<float> binding{{static_cast<const float*>(a.buffer.buf),std::size_t(n)},unary?std::span<const float>{}:std::span<const float>{static_cast<const float*>(b.buffer.buf),std::size_t(n)},{static_cast<const float*>(da.buffer.buf),std::size_t(n)},unary?std::span<const float>{}:std::span<const float>{static_cast<const float*>(db.buffer.buf),std::size_t(n)},{},{output.data(),output.size()},{},{}};nn::local_status status;Py_BEGIN_ALLOW_THREADS status=df::local_jvp(operation,binding); Py_END_ALLOW_THREADS if(status!=nn::local_status::success){PyErr_SetString(PyExc_RuntimeError,"native Cellerator JVP rejected binding");return nullptr;}PyObject*result=PyList_New(n);if(!result)return nullptr;for(Py_ssize_t i=0;i<n;++i)PyList_SET_ITEM(result,i,PyFloat_FromDouble(output[std::size_t(i)]));return result;}
PyObject* capabilities(PyObject*,PyObject*){PyObject*d=PyDict_New();if(!d)return nullptr;PyDict_SetItemString(d,"host_jvp",Py_True);PyDict_SetItemString(d,"host_vjp",Py_True);PyDict_SetItemString(d,"gpu_interchange",Py_False);PyDict_SetItemString(d,"gpu_interchange_reason",PyUnicode_FromString("unsupported: no stream and lifetime contract"));return d;}
PyMethodDef methods[]={{"jvp",jvp,METH_VARARGS,"Run Cellerator host local JVP on strict float32 contiguous buffers."},{"capabilities",capabilities,METH_NOARGS,"Return native binding capabilities."},{nullptr,nullptr,0,nullptr}};
PyModuleDef module={PyModuleDef_HEAD_INIT,"glasshelix_nf1",nullptr,-1,methods};
} PyMODINIT_FUNC PyInit_glasshelix_nf1(){return PyModule_Create(&module);}
