#include <GlassHelix/inference/inference.hh>
#include <Cellerator/compute/operation/native_numeric/device_linear.hh>
#include <cuda_runtime_api.h>
#include <cmath>
#include <cstdio>
#include <stdexcept>
#include <vector>
namespace ce=cellerator::compute::native_numeric; namespace pg=cellerator::execution::program; namespace gh=glasshelix;
void ok(cudaError_t e){if(e!=cudaSuccess)throw std::runtime_error("cuda");} void need(bool x,const char* m){if(!x)throw std::runtime_error(m);}
struct vec { ce::resident_vector v{}; vec(){ok(ce::allocate(&v,1,ce::device_representation::f32,0));} ~vec(){ce::release(&v);} };
gh::core::quantity q(){gh::core::quantity x; x.axis={{gh::core::identity::biological_abi_version,gh::core::identity::serialized_record_kind::persistent_axis_identity,sizeof(gh::core::identity::persistent_axis_identity)},{1,0},{2,0},{3,0},{4,0}};x.structure={5,0};x.units="r";x.role=gh::core::quantity_role::observation;x.extent=1;return x;}
gh::core::result_provenance prov(){gh::core::result_provenance p;p.scientific_model_id="system";p.model_revision="r1";p.gh_source_commit="gh";p.ce_source_commit="ce";p.numerical_policy="fp32";return p;}
struct ce_path { vec input[2], output[2]; pg::prepared_program_v2 program; ce_path():program{} { static ce::linear_stage d{ce::linear_kind::axpby,1,ce::device_representation::f32,2.f,0.f}; static pg::prepared_stage_v2 st=ce::make_linear_stage(9,1,&d); program={2,0,&st,1,nullptr,0}; }
  std::vector<pg::launch_binding_v2> bind(const gh::inference::candidate& c) { const auto slot=c.hypothesis_id=="left"?0:1; const float x=static_cast<float>(c.joint_state.at(0)); ok(ce::upload(input[slot].v,&x,1,{1},nullptr)); return {{input[slot].v.data,output[slot].v.data,input[slot].v.data}}; }
  gh::observation::engine_output collect(const gh::inference::candidate& c) { const auto slot=c.hypothesis_id=="left"?0:1; float y=0;ok(ce::download(output[slot].v,&y,1,nullptr));ok(cudaDeviceSynchronize());need(std::abs(y-2.f*static_cast<float>(c.joint_state.at(0)))<1e-6f,"CE result differs from 2*x");return {{y},prov()}; }
};
int main()try { ce_path path; auto observed=q();auto map=gh::observation::observation_map::partial(observed,1,{0});gh::core::observation_record evidence{observed,{.5},{true},"r","h","s","g",1,gh::core::sampling_unit::population_snapshot,true}; gh::observation::gaussian_noise noise{1.,1};
  gh::inference::finite_candidates belief{{{"left","m1",{0},.5},{"right","m2",{1},.5}}}; belief.propagate_ce(path.program,[&](auto const& c){return path.bind(c);},[&](auto const& c){return path.collect(c);},nullptr); belief.assimilate(evidence,noise,map,"e1"); const auto expected=1.0/(1.0+std::exp(-1.0)); need(std::abs(belief.values()[0].weight-expected)<1e-9&&std::abs(belief.values()[1].weight-(1-expected))<1e-9,"normalized moderate posterior wrong");need(belief.values()[0].mechanism_id=="m1"&&belief.values()[1].mechanism_id=="m2"&&belief.evidence_history()==std::vector<std::string>{"e1"},"joint identity/history lost");
  gh::inference::finite_candidates same{{{"left","m-left",{.25},.5},{"right","m-right",{.25},.5}}}; same.propagate_ce(path.program,[&](auto const& c){return path.bind(c);},[&](auto const& c){return path.collect(c);},nullptr); auto same_evidence=evidence;same_evidence.values[0]=.5;same.assimilate(same_evidence,noise,map,"same");need(std::abs(same.values()[0].weight-.5)<1e-12&&std::abs(same.values()[1].weight-.5)<1e-12&&same.values()[0].mechanism_id!="m-right","indistinguishable alternatives collapsed");
  gh::inference::finite_candidates invalid{{{"left","bad",{0},.5},{"right","bad2",{1},.5}}};int collected=0;bool failed=false;try{invalid.propagate_ce(path.program,[](auto const&){return std::vector<pg::launch_binding_v2>{};},[&](auto const&){++collected;return gh::observation::engine_output{{0},prov()};},nullptr);}catch(const std::runtime_error&){failed=true;}need(failed&&collected==0,"invalid CE binding reached collector");bool no_partial=false;try{invalid.assimilate(evidence,noise,map,"bad");}catch(const std::logic_error&){no_partial=true;}need(no_partial,"partial CE predictions assimilated");return 0;}catch(const std::exception& e){std::fprintf(stderr,"%s\n",e.what());return 1;}
