add_executable(gh_nf1a_diagnostics diagnostics.cc)
target_link_libraries(gh_nf1a_diagnostics PRIVATE GlassHelix::core LAPACK::LAPACK)
add_test(NAME gh_nf1a_diagnostics COMMAND gh_nf1a_diagnostics)
add_executable(gh_nf1a_alternatives alternatives.cc)
target_link_libraries(gh_nf1a_alternatives PRIVATE GlassHelix::core)
add_test(NAME gh_nf1a_alternatives COMMAND gh_nf1a_alternatives)
enable_language(CUDA)
add_executable(gh_nf1a_differentiate differentiate.cu)
target_link_libraries(gh_nf1a_differentiate PRIVATE GlassHelix::core Cellerator::native_foundation CUDA::cudart)
set_target_properties(gh_nf1a_differentiate PROPERTIES CUDA_STANDARD 20 CUDA_STANDARD_REQUIRED YES)
add_test(NAME gh_nf1a_differentiate COMMAND gh_nf1a_differentiate)
