#include <GlassHelix/dynamics/response_plan.hh>
#include <GlassHelix/interrogation/differentiation.hh>
#include <cuda_runtime_api.h>
#include <array>
#include <cmath>
#include <stdexcept>
#include <vector>
namespace gh=glasshelix::interrogation; namespace df=gh::df; namespace nf=gh::nf; namespace nn=cellerator::compute::native_numeric; namespace ex=cellerator::execution;
void ok(bool v){if(!v)throw std::runtime_error("differentiate");} void gpu(cudaError_t e){ok(e==cudaSuccess);} struct V{nn::resident_vector x{};V(cudaStream_t s,const std::vector<float>&h,std::uint64_t g=1){gpu(nn::allocate(&x,h.size(),nn::device_representation::f32,0));gpu(nn::upload(x,h.data(),h.size(),{g},s));}~V(){nn::release(&x);}};
nf::primal_record primal(nf::identity d){nf::primal_record p{};p.instance.prepared={d,{2,1},{1},{3,1}};p.instance.state={{4,1},{7}};p.instance.parameters={{5,1},{11}};return p;}
int main(){cudaStream_t s{};gpu(cudaStreamCreateWithFlags(&s,cudaStreamNonBlocking));constexpr int n=33;std::vector<float>a(n,2),b(n,3),da(n,.1f),db(n,.2f),z(n);V A(s,a,7),B(s,b,11),DA(s,da),DB(s,db),O(s,z),S(s,a,7),P(s,b,11);std::array<nf::operand_signature,2> in{{{{10,1},{},n,ex::numeric_type::f32},{{11,1},{},n,ex::numeric_type::f32}}};nf::output_signature out{{{12,1},{},n,ex::numeric_type::f32},{13,1}};nf::operation_contract c{};c.definition={100,1};c.arguments={in.data(),2};c.outputs={&out,1};c.numeric={ex::numeric_type::f32,ex::numeric_type::f32,ex::numeric_type::f32,ex::numeric_type::f32,ex::numeric_type::f32,ex::numeric_type::f32};c.capabilities=nf::forward|nf::jvp;df::local_primal_owners owners{&A.x,&B.x,&S.x,&P.x,s,primal(c.definition)};df::local_block block{};ok(df::make_local_device_block(nn::local_operation::multiply,c,owners,block)==nf::status::success);df::response_binding<float> r{};r.left_direction=&DA.x;r.right_direction=&DB.x;r.output=&O.x;r.count=n;r.request.action=nf::jvp;r.request.primal=primal(c.definition);r.request.direction_domain=in[0];r.request.response_domain=out.operand;r.direction=in[0];r.response=out.operand;glasshelix::core::response_request q{glasshelix::core::differentiated_object::vector_field,glasshelix::core::forward_request{}, {}};gh::vector_field_primal stamp{7,11,13,17,gh::primal_policy::saved};ok(gh::execute_vector_field_jvp(q,stamp,stamp,block,r,s)==gh::pg::program_status::success);std::vector<float>got(n);gpu(nn::download(O.x,got.data(),n,s));gpu(cudaStreamSynchronize(s));for(float x:got)ok(std::abs(x-.7f)<1e-5f);auto stale=stamp;stale.forcing++;ok(gh::execute_vector_field_jvp(q,stamp,stale,block,r,s)==gh::pg::program_status::launch_failed);q.object=glasshelix::core::differentiated_object::discrete_step;ok(gh::execute_vector_field_jvp(q,stamp,stamp,block,r,s)==gh::pg::program_status::invalid_argument);cudaStreamDestroy(s);}
