# Native scientific library; lower-level execution stays in Cellerator.
set(GH_NF1_CONTRACT_ROOT "${PROJECT_SOURCE_DIR}" CACHE PATH "Integrated scientific contract checkout")
set(GH_NF1_CONTRACT_COMMIT "" CACHE STRING "Required commit for an external developmental contract checkout")
set(CELLERATOR_SOURCE_ROOT "" CACHE PATH "Integrated Cellerator checkout providing canonical identities")
if(NOT EXISTS "${GH_NF1_CONTRACT_ROOT}/include/GlassHelix/core/system.hh")
  message(FATAL_ERROR "Integrate the C contracts or provide GH_NF1_CONTRACT_ROOT and its pinned commit")
endif()
if(NOT GH_NF1_CONTRACT_ROOT STREQUAL PROJECT_SOURCE_DIR)
  if(GH_NF1_CONTRACT_COMMIT STREQUAL "")
    message(FATAL_ERROR "External scientific contracts require GH_NF1_CONTRACT_COMMIT")
  endif()
  execute_process(COMMAND git -C "${GH_NF1_CONTRACT_ROOT}" rev-parse HEAD OUTPUT_VARIABLE contract_head OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  if(NOT contract_head STREQUAL GH_NF1_CONTRACT_COMMIT)
    message(FATAL_ERROR "External scientific contract source differs from pinned commit")
  endif()
  execute_process(COMMAND git -C "${GH_NF1_CONTRACT_ROOT}" diff --quiet HEAD -- include/GlassHelix/core RESULT_VARIABLE contract_dirty)
  if(NOT contract_dirty EQUAL 0)
    message(FATAL_ERROR "External scientific contract headers have uncommitted changes")
  endif()
endif()
if(NOT EXISTS "${CELLERATOR_SOURCE_ROOT}/include/Cellerator/execution/identity.hh")
  message(FATAL_ERROR "CELLERATOR_SOURCE_ROOT must provide integrated Cellerator identities")
endif()
add_library(glasshelix_foundation STATIC "${PROJECT_SOURCE_DIR}/src/core/host_bindings.cc")
add_library(GlassHelix::foundation ALIAS glasshelix_foundation)
target_compile_features(glasshelix_foundation PUBLIC cxx_std_20)
set_target_properties(glasshelix_foundation PROPERTIES CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON)
target_include_directories(glasshelix_foundation PUBLIC
  "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>"
  "$<BUILD_INTERFACE:${GH_NF1_CONTRACT_ROOT}/include>"
  "$<BUILD_INTERFACE:${CELLERATOR_SOURCE_ROOT}/include>")
if(BUILD_TESTING)
  add_subdirectory(tests/native_foundation/build)
endif()
