#!/usr/bin/env python3
"""Rehash reviewed planning/example files. Does not validate science, native schema or authority."""
from pathlib import Path
import argparse,hashlib,json,sys
sys.dont_write_bytecode=True
PACKAGE=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    a=argparse.ArgumentParser(description=__doc__);a.add_argument('--confirm',required=True);o=a.parse_args()
    if o.confirm!='SEAL-NF1-PACKAGE':raise ValueError('Wrong confirmation')
    delivery=PACKAGE/'machine/delivery_files.json';d=json.loads(delivery.read_text())
    for f in d['files']:
        path=PACKAGE.parents[1]/f['path']
        if not path.is_file() or path.is_symlink() or not path.resolve().is_relative_to(PACKAGE.parents[1]):raise ValueError('Unsafe/missing delivered file')
        f['sha256']=sha(path)
    delivery.write_text(json.dumps(d,indent=2)+'\n')
    files=sorted(p for p in PACKAGE.rglob('*') if p.is_file() and p!=PACKAGE/'MANIFEST.sha256')
    if any(p.is_symlink() or '__pycache__' in p.parts or p.suffix=='.pyc' for p in files):raise ValueError('Symlink or generated bytecode in package')
    (PACKAGE/'MANIFEST.sha256').write_text(''.join(sha(p)+'  '+p.relative_to(PACKAGE).as_posix()+'\n' for p in files))
    print(json.dumps({'sealed_files':len(files),'authority_mutated':False,'note':'Re-run validation. Hashing is not an approval of changed content.'}))
if __name__=='__main__':
    try:main()
    except (ValueError,KeyError,OSError) as e:raise SystemExit(str(e))
